services:
  ? adp-test-dr-11
  : command: npm run start:watch
    build:
      target: development
    image: adp-test-dr-11-development
    environment:
      NODE_ENV: test
    volumes:
    - ./test-output:/home/node/test-output

  axe:
    image: defradigital/ffc-axe
    depends_on:
      - adp-test-dr-11
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        /scripts/wait ${TEST_ENVIRONMENT_ROOT_URL:-adp-test-dr-11:3000} -- axe --dir=test-output -s axe.json --report=test-output --format=junit --exclude ".govuk-skip-link,.govuk-breadcrumbs"  --chrome-options="no-sandbox,disable-setuid-sandbox,disable-dev-shm-usage" --chromedriver-path=/usr/bin/chromedriver --exit  ${TEST_ENVIRONMENT_ROOT_URL:-adp-test-dr-11:3000}
    volumes:
      - ./test-output/axe:/home/node/test-output
      - ./scripts:/scripts
