{{- include "adp-helm-library.deployment" (list . "adp-test-dr-11.deployment") -}}
{{- define "adp-test-dr-11.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "adp-test-dr-11.container") }}
{{- end -}}
